name: 'Dependabot Alert Policy Checker'
description: 'Checks Dependabot alerts against configurable age thresholds and fails if alerts exceed their age limits'
author: 'Your Name'

inputs:
  critical-threshold:
    description: 'Maximum age in days for Critical severity alerts'
    required: false
    default: '3'
  high-threshold:
    description: 'Maximum age in days for High severity alerts'
    required: false
    default: '5'
  medium-threshold:
    description: 'Maximum age in days for Medium severity alerts'
    required: false
    default: '14'
  low-threshold:
    description: 'Maximum age in days for Low severity alerts'
    required: false
    default: '30'
  github-token:
    description: 'GitHub token with security alerts read permission'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub
    
    - name: Run alert checker
      shell: bash
      env:
        INPUT_CRITICAL_THRESHOLD: ${{ inputs.critical-threshold }}
        INPUT_HIGH_THRESHOLD: ${{ inputs.high-threshold }}
        INPUT_MEDIUM_THRESHOLD: ${{ inputs.medium-threshold }}
        INPUT_LOW_THRESHOLD: ${{ inputs.low-threshold }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: python ${{ github.action_path }}/check_alerts.py
